apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rw6bjfj85-python 
  janus-idp.io/tekton: rw6bjfj85-python
  backstage.io/kubernetes-id: rw6bjfj85-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rw6bjfj85-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml