apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rw6bjfj85-python
  janus-idp.io/tekton: rw6bjfj85-python
  backstage.io/kubernetes-id: rw6bjfj85-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rw6bjfj85-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
