apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rw6bjfj85-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rw6bjfj85-python 
  name: rw6bjfj85-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rw6bjfj85-python 
